version: '3'
services:
  app:
    image: hello-k8s-app
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    env_file:
      - .env
    volumes: ["logs:/app/storage/logs"]

  nginx:
    image: hello-k8s-nginx
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    environment:
      PHP_FPM_HOST: app
    ports:
      - 8000:80
    depends_on:
      - app

  app-log-tail:
    build:
      context: .
      dockerfile: docker/tail/Dockerfile
    image: hello-k8s-tail
    environment:
      WATCHED_FILE: "/tmp/laravel.log"
    volumes: ["logs:/tmp"]

volumes:
  logs:
