apiVersion: v1
kind: Service
metadata:
  name: hello-k8s
  annotations:
    app.kubernetes.io/version: 0.1.0
    app.kubernetes.io/managed-by: "PHL"
    app.kubernetes.io/name: hello-k8s
    app.kubernetes.io/instance: local

spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: hello-k8s
    app.kubernetes.io/instance: local

  ports:
    - port: 80
      targetPort: 80
      nodePort: 32000
      protocol: TCP
